// <auto-generated/>
using System;
using Code.Core.ServiceLocator;
using Code.Game.Characters.Player;

namespace Game
{
    public partial class GameInstaller : IAssemblyInstaller
    {
        public int Order { get; }
       
        public Type[] GetServiceOrder() => new[]
        {
            typeof(PlayerInput),
        };
    }
}
