// <auto-generated/>
using System;
using Code.Core.ServiceLocator;

namespace Game
{
    public partial class GameInstaller : IAssemblyInstaller
    {
        public int Order { get; }
        public Type[] GetServiceOrder() => new[]
        {
            typeof(Code.Game.PlayerInput),
        };
    }
}
